version: '3'
services:
  pgsql:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'bling_test'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'